import './globals.css'
import { Inter } from 'next/font/google'
import { UploadedImagesProvider } from "../context/uploadedImages"
import { ClassesProvider } from '@/context/classes'
import { ProjectProvider } from '@/context/project'
import { PolygonsProvider } from '@/context/polygons'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProjectProvider>
          <ClassesProvider>
            <UploadedImagesProvider>
              <PolygonsProvider>
                {children}
              </PolygonsProvider>
            </UploadedImagesProvider>
          </ClassesProvider>
        </ProjectProvider>
      </body>
    </html>
  )
}
